window:
    dimensions:
        columns: 0
        lines: 0

    padding:
        x: 0
        y: 0


    # Windows の装飾
    #
    # - full: タイトルバーとボーダー
    # - none: タイトルバーもボーダーも非表示
    #
    # macOSのみ
    # - transparent: タイトルバーが透明
    # - buttonless: タイトルバーが透明でボタンもなし
    #
    decorations: full

    # 起動時
    #
    # - Windowed
    # - Maximized
    # - Fullscreen
    startup_mode: Windowed

scrolling:
    # スクロールのために保持する行数
    history: 10000

    # 行をスクロールした際に動く行数
    multiplier: 3

tabspaces: 4

font:
    size: 14.0

    # macOS のみ
    #
    # 線が細いフォントを描画する
    # Retinaディスプレイに適している
    use_thin_strokes: true

# bold フォントが明るい色で描画される
draw_bold_text_with_bright_colors: true

colors:
    primary:
        background: '0x000000'
        foreground: '0xeaeaea'

    selection:
        text: '0xeaeaea'
        background: '0x404040'

    normal:
        black:   '0x000000'
        red:     '0xd54e53'
        green:   '0xb9ca4a'
        yellow:  '0xe6c547'
        blue:    '0x7aa6da'
        magenta: '0xc397d8'
        cyan:    '0x70c0ba'
        white:   '0xeaeaea'

    bright:
        black:   '0x666666'
        red:     '0xff3334'
        green:   '0x9ec400'
        yellow:  '0xe7c547'
        blue:    '0x7aa6da'
        magenta: '0xb77ee0'
        cyan:    '0x54ced6'
        white:   '0xffffff'

visual_bell:
    animation: EaseOutExpo
    duration: 0
    color: '0xffffff'

background_opacity: 0.8

dynamic_title: true

cursor:

    # カーソルのスタイル
    #
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    style: Block

    # フォーカスされていないときは表示を変える
    unfocused_hollow: true

live_config_reload: true
